[package]
name = "Rust"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = "0.5.1"
dotenvy = "0.15.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rocket_cors = "0.6.0"
